import tseslint from "typescript-eslint";
import sonarjs from "eslint-plugin-sonarjs";

const sonarCodeSmellRules = {
  "sonarjs/arguments-usage": "error",
  "sonarjs/array-constructor": "error",
  "sonarjs/arrow-function-convention": ["error", { requireParameterParentheses: true }],
  "sonarjs/bool-param-default": "error",
  "sonarjs/class-prototype": "error",
  "sonarjs/conditional-indentation": "error",
  "sonarjs/cyclomatic-complexity": ["error", { threshold: 10 }],
  "sonarjs/destructuring-assignment-syntax": "error",
  "sonarjs/elseif-without-else": "error",
  "sonarjs/enforce-trailing-comma": "error",
  "sonarjs/expression-complexity": ["error", { max: 3 }],
  "sonarjs/for-in": "error",
  "sonarjs/function-name": "error",
  "sonarjs/max-lines": ["error", { maximum: 150 }],
  "sonarjs/max-lines-per-function": ["error", { maximum: 80 }],
  "sonarjs/max-union-size": ["error", { threshold: 5 }],
  "sonarjs/nested-control-flow": "error",
  "sonarjs/no-built-in-override": "error",
  "sonarjs/no-collapsible-if": "error",
  "sonarjs/no-duplicate-string": "error",
  "sonarjs/no-for-in-iterable": "error",
  "sonarjs/no-function-declaration-in-block": "error",
  "sonarjs/no-inconsistent-returns": "error",
  "sonarjs/no-incorrect-string-concat": "error",
  "sonarjs/no-nested-incdec": "error",
  "sonarjs/no-nested-switch": "error",
  "sonarjs/no-redundant-parentheses": "error",
  "sonarjs/no-tab": "error",
  "sonarjs/no-undefined-assignment": "error",
  "sonarjs/no-unused-function-argument": "error",
  "sonarjs/no-variable-usage-before-declaration": "error",
  "sonarjs/non-number-in-arithmetic-expression": "error",
  "sonarjs/operation-returning-nan": "error",
  "sonarjs/prefer-immediate-return": "error",
  "sonarjs/prefer-object-literal": "error",
  "sonarjs/regular-expr": "error",
  "sonarjs/shorthand-property-grouping": "error",
  "sonarjs/strings-comparison": "error",
  "sonarjs/too-many-break-or-continue-in-loop": "error",
  "sonarjs/unicode-aware-regex": "error",
  "sonarjs/useless-string-operation": "error",
  "sonarjs/values-not-convertible-to-numbers": "error",
  "sonarjs/variable-name": "error",
};

export default tseslint.config(
  {
    ignores: ["**/dist/**"],
  },
  ...tseslint.configs.recommended,
  sonarjs.configs.recommended,
  {
    files: ["src/**/*.ts"],
    rules: {
      ...sonarCodeSmellRules,
    },
  },
);
